package interfaz;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel; //Para crear el modelo de la TABLA
import javax.swing.table.JTableHeader;

public class frmReporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReporte
     */
    public frmReporte() {
        initComponents();
    }

    //Detectar la tecla enter
    private boolean teclaEnter(java.awt.event.KeyEvent evt) {
        boolean result = false;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            result = true;
        }
        return result;
    }

    //Realizar verficiacion de que sea tipo:codigo
    private boolean verificarInputBuscarEmpleadoxArticulo() {
        boolean result = false;

        String consulta = buscadorReporte.getText();
        String tipoBusqueda = consulta.trim().toLowerCase();

        String regex = "(.)*\\:(\\d)(.)*";

        //Verificar que el formato de la consulta si sea tipo:codigo
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(consulta);
        boolean isMatched = matcher.matches();

        if ((tipoBusqueda.indexOf("empleado") != -1 && isMatched) || (tipoBusqueda.indexOf("articulo") != -1 && isMatched)) {
            result = true;
        }

        return result;
    }

    //Realizar busqued para las tablas Empleados X Articulos
    private void realizarBusquedaEmpleadoxArticulo() {
        String consulta = buscadorReporte.getText();
        String[] separador = consulta.split(":");
        String tipoBusqueda = separador[0].trim().toLowerCase();
        String codigoBusqueda = separador[1].trim();

        System.out.println("separador: " + separador);

        System.out.println("Buscar id empleado en la tabla ventas");

        String titulosEmpleadoVentas[] = {"código", "cod_emp", "cod_cli", "cod_art", "Cant", "Valor", "Fecha", "Hora"}; //titulo de las columnas
        String infoEmpleadoVentas1 = "fila 1,002,001,003,10,150000,02-05-2020,8:30:36"; // Información que se va a enviar a la tabla
        String infoEmpleadoVentas2 = "fila 2,003,004,005,2,3000,05-05-2010,8:20:36"; // Información que se va a enviar a la tabla
        String[] lineaEmpleadoVentas; // Array que almacenara la información separa por , en cada indice
        DefaultTableModel modeloEmpleadoVentas = new DefaultTableModel(); //Crear el modelo a la tabla

        modeloEmpleadoVentas.setColumnIdentifiers(titulosEmpleadoVentas); //Asignar titulos a la tabla
        String[] lineaEmpleadoVentas1 = infoEmpleadoVentas1.split(",");
        String[] lineaEmpleadoVentas2 = infoEmpleadoVentas2.split(",");
        modeloEmpleadoVentas.addRow(lineaEmpleadoVentas1); //Asignar el mododelo a la tabla
        modeloEmpleadoVentas.addRow(lineaEmpleadoVentas2);
        tabla_resultadoGeneral.setModel(modeloEmpleadoVentas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicial = new javax.swing.JPanel();
        cont_titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_filtrarLista = new javax.swing.JButton();
        list_buscador = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        tabla_principalVentas = new javax.swing.JScrollPane();
        tabla_ventas = new javax.swing.JTable();
        tabla_clientePrincipal = new javax.swing.JScrollPane();
        tabla_clienteInterna = new javax.swing.JTable();
        tabla_empleadoPrincipal = new javax.swing.JScrollPane();
        tabla_empleadoInterna = new javax.swing.JTable();
        tabla_articuloPrincipal = new javax.swing.JScrollPane();
        tabla_articuloInterna = new javax.swing.JTable();
        tituloCliente = new javax.swing.JPanel();
        lbl_infoCliente = new javax.swing.JLabel();
        tituloEmpleado = new javax.swing.JPanel();
        lbl_infoEmpleado = new javax.swing.JLabel();
        tituloEmpleado1 = new javax.swing.JPanel();
        lbl_infoEmpleado1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btn_buscar = new javax.swing.JButton();
        buscadorReporte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tabla_principal_empleadoxarticulo = new javax.swing.JScrollPane();
        tabla_empleadoxarticulo = new javax.swing.JTable();
        tabla_principal_resultadoGenerales = new javax.swing.JScrollPane();
        tabla_resultadoGeneral = new javax.swing.JTable();
        piePagina = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1200, 905));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        panelInicial.setBackground(new java.awt.Color(255, 255, 255));

        cont_titulo.setBackground(new java.awt.Color(46, 53, 137));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Days One", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("REPORTES");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Consultar CLIENTES, EMPLEADOS, ARTICULOS Y VENTAS realizadas.");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout cont_tituloLayout = new javax.swing.GroupLayout(cont_titulo);
        cont_titulo.setLayout(cont_tituloLayout);
        cont_tituloLayout.setHorizontalGroup(
            cont_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cont_tituloLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        cont_tituloLayout.setVerticalGroup(
            cont_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cont_tituloLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btn_filtrarLista.setBackground(new java.awt.Color(74, 79, 231));
        btn_filtrarLista.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_filtrarLista.setForeground(new java.awt.Color(255, 255, 255));
        btn_filtrarLista.setText("Realizar búsqueda");
        btn_filtrarLista.setBorder(null);
        btn_filtrarLista.setBorderPainted(false);
        btn_filtrarLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_filtrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtrarListaActionPerformed(evt);
            }
        });

        list_buscador.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        list_buscador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar clientes", "Mostrar empleados", "Mostrar articulos", "Mostrar ventas" }));
        list_buscador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(list_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_filtrarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_filtrarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(list_buscador, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tabla_ventas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_ventasMouseClicked(evt);
            }
        });
        tabla_principalVentas.setViewportView(tabla_ventas);

        tabla_clientePrincipal.setBackground(new java.awt.Color(255, 255, 255));

        tabla_clienteInterna.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla_clienteInterna.setForeground(new java.awt.Color(51, 51, 51));
        tabla_clienteInterna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_clienteInterna.setAutoscrolls(false);
        tabla_clienteInterna.setGridColor(new java.awt.Color(102, 102, 102));
        tabla_clienteInterna.setRowHeight(20);
        tabla_clienteInterna.setRowMargin(5);
        tabla_clientePrincipal.setViewportView(tabla_clienteInterna);

        tabla_empleadoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        tabla_empleadoPrincipal.setOpaque(false);

        tabla_empleadoInterna.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla_empleadoInterna.setForeground(new java.awt.Color(51, 51, 51));
        tabla_empleadoInterna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_empleadoInterna.setAutoscrolls(false);
        tabla_empleadoInterna.setGridColor(new java.awt.Color(204, 204, 204));
        tabla_empleadoInterna.setRowHeight(20);
        tabla_empleadoInterna.setRowMargin(5);
        tabla_empleadoPrincipal.setViewportView(tabla_empleadoInterna);

        tabla_articuloPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        tabla_articuloPrincipal.setOpaque(false);

        tabla_articuloInterna.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla_articuloInterna.setForeground(new java.awt.Color(51, 51, 51));
        tabla_articuloInterna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_articuloInterna.setAutoscrolls(false);
        tabla_articuloInterna.setGridColor(new java.awt.Color(204, 204, 204));
        tabla_articuloInterna.setRowHeight(20);
        tabla_articuloInterna.setRowMargin(5);
        tabla_articuloPrincipal.setViewportView(tabla_articuloInterna);

        tituloCliente.setBackground(new java.awt.Color(74, 79, 231));

        lbl_infoCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_infoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_infoCliente.setText("Información Cliente:");
        lbl_infoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout tituloClienteLayout = new javax.swing.GroupLayout(tituloCliente);
        tituloCliente.setLayout(tituloClienteLayout);
        tituloClienteLayout.setHorizontalGroup(
            tituloClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_infoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tituloClienteLayout.setVerticalGroup(
            tituloClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_infoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        tituloEmpleado.setBackground(new java.awt.Color(74, 79, 231));

        lbl_infoEmpleado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_infoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_infoEmpleado.setText("Información Empleado:");
        lbl_infoEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout tituloEmpleadoLayout = new javax.swing.GroupLayout(tituloEmpleado);
        tituloEmpleado.setLayout(tituloEmpleadoLayout);
        tituloEmpleadoLayout.setHorizontalGroup(
            tituloEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_infoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tituloEmpleadoLayout.setVerticalGroup(
            tituloEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_infoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        tituloEmpleado1.setBackground(new java.awt.Color(74, 79, 231));

        lbl_infoEmpleado1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_infoEmpleado1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_infoEmpleado1.setText("Información Articulo:");
        lbl_infoEmpleado1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout tituloEmpleado1Layout = new javax.swing.GroupLayout(tituloEmpleado1);
        tituloEmpleado1.setLayout(tituloEmpleado1Layout);
        tituloEmpleado1Layout.setHorizontalGroup(
            tituloEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloEmpleado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_infoEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tituloEmpleado1Layout.setVerticalGroup(
            tituloEmpleado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_infoEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(tabla_principalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabla_articuloPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(tabla_empleadoPrincipal)
                    .addComponent(tituloCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabla_clientePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloEmpleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(tituloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabla_clientePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tituloEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabla_empleadoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(tituloEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabla_articuloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabla_principalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btn_buscar.setBackground(new java.awt.Color(74, 79, 231));
        btn_buscar.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Realizar búsqueda");
        btn_buscar.setBorder(null);
        btn_buscar.setBorderPainted(false);
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        buscadorReporte.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        buscadorReporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscadorReporte.setText("Empleado:código o Articulo:codigo");
        buscadorReporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscadorReporteFocusLost(evt);
            }
        });
        buscadorReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscadorReporteMouseClicked(evt);
            }
        });
        buscadorReporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscadorReporteKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        jLabel3.setText("Consultar mediante el código del empleado o articulo. *empleado:codigo o articulo:codigo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(buscadorReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(543, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscadorReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
        );

        tabla_empleadoxarticulo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla_empleadoxarticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_empleadoxarticulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla_empleadoxarticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_empleadoxarticuloMouseClicked(evt);
            }
        });
        tabla_principal_empleadoxarticulo.setViewportView(tabla_empleadoxarticulo);

        tabla_resultadoGeneral.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tabla_resultadoGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla_resultadoGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla_resultadoGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_resultadoGeneralMouseClicked(evt);
            }
        });
        tabla_principal_resultadoGenerales.setViewportView(tabla_resultadoGeneral);

        piePagina.setBackground(new java.awt.Color(46, 53, 137));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Todos los derechos reservados - copyright 2020 - - - Versión de software 1.0 - - - Tech & chill");

        javax.swing.GroupLayout piePaginaLayout = new javax.swing.GroupLayout(piePagina);
        piePagina.setLayout(piePaginaLayout);
        piePaginaLayout.setHorizontalGroup(
            piePaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piePaginaLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        piePaginaLayout.setVerticalGroup(
            piePaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelInicialLayout = new javax.swing.GroupLayout(panelInicial);
        panelInicial.setLayout(panelInicialLayout);
        panelInicialLayout.setHorizontalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cont_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicialLayout.createSequentialGroup()
                        .addComponent(tabla_principal_resultadoGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tabla_principal_empleadoxarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
            .addComponent(piePagina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelInicialLayout.setVerticalGroup(
            panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cont_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabla_principal_empleadoxarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabla_principal_resultadoGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(piePagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filtrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtrarListaActionPerformed

        String resultLista = list_buscador.getSelectedItem().toString();

        switch (resultLista) {
            case "Mostrar clientes":
                String titulosClientes[] = {"cliente 1", "cliente 2", "cliente 3", "cliente 4"}; //titulo de las columnas
                String info = "1,2,3,4"; // Información que se va a enviar a la tabla
                String[] lineaClientes; // Array que almacenara la información separa por , en cada indice
                DefaultTableModel modeloCliente = new DefaultTableModel(); //Crear el modelo a la tabla

                modeloCliente.setColumnIdentifiers(titulosClientes); //Asignar titulos a la tabla
                lineaClientes = info.split(",");
                modeloCliente.addRow(lineaClientes); //Asignar el mododelo a la tabla
                tabla_ventas.setModel(modeloCliente);
                ;
                break;
            case "Mostrar ventas":
                String titulosVentas[] = {"código", "cod_emp", "cod_cli", "cod_art", "Cant", "Valor", "Fecha", "Hora"}; //titulo de las columnas
                String infoVentas1 = "fila 1,002,001,003,10,150000,02-05-2020,8:30:36"; // Información que se va a enviar a la tabla
                String infoVentas2 = "fila 2,003,004,005,2,3000,05-05-2010,8:20:36"; // Información que se va a enviar a la tabla
                String[] lineaVentas; // Array que almacenara la información separa por , en cada indice
                DefaultTableModel modeloVenta = new DefaultTableModel(); //Crear el modelo a la tabla

                modeloVenta.setColumnIdentifiers(titulosVentas); //Asignar titulos a la tabla
                String[] lineaVentas1 = infoVentas1.split(",");
                String[] lineaVentas2 = infoVentas2.split(",");
                modeloVenta.addRow(lineaVentas1); //Asignar el mododelo a la tabla
                modeloVenta.addRow(lineaVentas2);
                tabla_ventas.setModel(modeloVenta);
        }

        if (!(list_buscador.getSelectedItem() == "Mostrar ventas")) {

            //Quitar información si no estoy en la tabla ventas
            System.out.println("Ya no es listado de ventas");
            DefaultTableModel modeloCliente = new DefaultTableModel(); //Crear el modelo a la tabla
            tabla_clienteInterna.setModel(modeloCliente);
            modeloCliente.setRowCount(0);

            DefaultTableModel modeloEmpleado = new DefaultTableModel(); //Crear el modelo a la tabla
            tabla_empleadoInterna.setModel(modeloEmpleado);
            modeloEmpleado.setRowCount(0);

            DefaultTableModel modeloArticulo = new DefaultTableModel(); //Crear el modelo a la tabla
            tabla_articuloInterna.setModel(modeloArticulo);
            modeloArticulo.setRowCount(0);
        }

    }//GEN-LAST:event_btn_filtrarListaActionPerformed

    private void tabla_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_ventasMouseClicked
        //Es almacenar la posicion de la fila seleccionada en la TABLA
        int fila = tabla_ventas.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla");
        } else {

            if (list_buscador.getSelectedItem() == "Mostrar ventas") {

                //TABLA CLIENTES
                String titulosClientes[] = {"Codigo", "Nombre", "Apellido", "Edad", "Dir", "Teléfono"}; //titulo de las columnas
                String infoCliente
                        = tabla_ventas.getValueAt(fila, 2).toString()
                        + ",Andrés"
                        + ",Serna Muñoz"
                        + ",24"
                        + ",Diagonal 58"
                        + ",601-00-00";

                String[] lineaClientes; // Array que almacenara la información separa por , en cada indice
                DefaultTableModel modeloCliente = new DefaultTableModel(); //Crear el modelo a la tabla

                modeloCliente.setColumnIdentifiers(titulosClientes); //Asignar titulos a la tabla
                String[] lineaCliente = infoCliente.split(",");
                modeloCliente.addRow(lineaCliente); //Asignar el mododelo a la tabla
                tabla_clienteInterna.setModel(modeloCliente);

                //TABLA EMPLEADOS
                String titulosEmpleados[] = {"Codigo", "Nombre", "Apellido", "Fecha nacimiento", "Teléfono", "Usuario", "Contraseña"}; //titulo de las columnas
                String infoEmpleado
                        = tabla_ventas.getValueAt(fila, 1).toString()
                        + ",Edwin"
                        + ",Palacios"
                        + ",10-05-2020"
                        + ",600-02-02"
                        + ",admin"
                        + ",123";

                String[] lineaEmpleados; // Array que almacenara la información separa por , en cada indice
                DefaultTableModel modeloEmpleado = new DefaultTableModel(); //Crear el modelo a la tabla

                modeloEmpleado.setColumnIdentifiers(titulosEmpleados); //Asignar titulos a la tabla
                lineaEmpleados = infoEmpleado.split(",");
                modeloEmpleado.addRow(lineaEmpleados); //Asignar el mododelo a la tabla
                tabla_empleadoInterna.setModel(modeloEmpleado);

                //TABLA ARTICULO
                String titulosArticulos[] = {"Codigo", "Titulo", "Género", "Precio", "Cantidad", "Tipo"}; //titulo de las columnas
                String infoArticulo
                        = tabla_ventas.getValueAt(fila, 3).toString()
                        + ",Intelestelar"
                        + ",Ciencia ficción"
                        + ",50000"
                        + ",2"
                        + ",Pelicula";

                String[] lineaArticulo; // Array que almacenara la información separa por , en cada indice
                DefaultTableModel modeloArticulo = new DefaultTableModel(); //Crear el modelo a la tabla

                modeloArticulo.setColumnIdentifiers(titulosArticulos); //Asignar titulos a la tabla
                lineaArticulo = infoArticulo.split(",");
                modeloArticulo.addRow(lineaArticulo); //Asignar el mododelo a la tabla
                tabla_articuloInterna.setModel(modeloArticulo);

            }

        }
    }//GEN-LAST:event_tabla_ventasMouseClicked

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        tabla_ventas.setCellSelectionEnabled(false);

    }//GEN-LAST:event_formInternalFrameActivated

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        if (verificarInputBuscarEmpleadoxArticulo()) {
            realizarBusquedaEmpleadoxArticulo();
        } else {
            System.out.println("Digitar el tipo de búsqueda y código correspondiente");
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tabla_empleadoxarticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_empleadoxarticuloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_empleadoxarticuloMouseClicked

    private void tabla_resultadoGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_resultadoGeneralMouseClicked
        String consulta = buscadorReporte.getText();
        String[] separador = consulta.split(":");
        String tipoBusqueda = separador[0].trim().toLowerCase();
        String codigoBusqueda = separador[1].trim();

        //Es almacenar la posicion de la fila seleccionada en la TABLA
        int fila = tabla_resultadoGeneral.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila de la tabla");
        } else {
            if (tipoBusqueda.equals("empleado")) {

                //TABLA ARTICULO
                String titulosArticulos[] = {"Codigo", "Titulo", "Género", "Precio", "Cantidad", "Tipo"}; //titulo de las columnas
                String infoArticulo
                        = tabla_resultadoGeneral.getValueAt(fila, 3).toString()
                        + ",Intelestelar"
                        + ",Ciencia ficción"
                        + ",50000"
                        + ",2"
                        + ",Pelicula";

                String[] lineaArticulo; // Array que almacenara la información separa por , en cada indice
                DefaultTableModel modeloArticulo = new DefaultTableModel(); //Crear el modelo a la tabla

                modeloArticulo.setColumnIdentifiers(titulosArticulos); //Asignar titulos a la tabla
                lineaArticulo = infoArticulo.split(",");
                modeloArticulo.addRow(lineaArticulo); //Asignar el mododelo a la tabla
                tabla_empleadoxarticulo.setModel(modeloArticulo);

            } else if (tipoBusqueda.equals("articulo")) {

                //TABLA EMPLEADOS
                String titulosEmpleados[] = {"Codigo", "Nombre", "Apellido", "Fecha nacimiento", "Teléfono", "Usuario", "Contraseña"}; //titulo de las columnas
                String infoEmpleado
                        = tabla_resultadoGeneral.getValueAt(fila, 1).toString()
                        + ",Edwin"
                        + ",Palacios"
                        + ",10-05-2020"
                        + ",600-02-02"
                        + ",admin"
                        + ",123";

                String[] lineaEmpleados; // Array que almacenara la información separa por , en cada indice
                DefaultTableModel modeloEmpleado = new DefaultTableModel(); //Crear el modelo a la tabla

                modeloEmpleado.setColumnIdentifiers(titulosEmpleados); //Asignar titulos a la tabla
                lineaEmpleados = infoEmpleado.split(",");
                modeloEmpleado.addRow(lineaEmpleados); //Asignar el mododelo a la tabla
                tabla_empleadoxarticulo.setModel(modeloEmpleado);

            }
        }
    }//GEN-LAST:event_tabla_resultadoGeneralMouseClicked

    private void buscadorReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscadorReporteMouseClicked
        buscadorReporte.requestFocus();
        buscadorReporte.selectAll();
    }//GEN-LAST:event_buscadorReporteMouseClicked

    private void buscadorReporteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscadorReporteFocusLost
        if (buscadorReporte.getText().equals("")) {

            buscadorReporte.setText("Empleado:código o Articulo:codigo");
        }
    }//GEN-LAST:event_buscadorReporteFocusLost

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        panelInicial.requestFocus();
    }//GEN-LAST:event_formMouseClicked

    private void buscadorReporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorReporteKeyPressed
        if (teclaEnter(evt)) {
            if (verificarInputBuscarEmpleadoxArticulo()) {
                realizarBusquedaEmpleadoxArticulo();
            } else {
                System.out.println("Digitar el tipo de búsqueda y código correspondiente");
            }

        }

    }//GEN-LAST:event_buscadorReporteKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PiedePagina;
    private javax.swing.JLabel PiedePagina1;
    private javax.swing.JLabel PiedePagina2;
    private javax.swing.JLabel PiedePagina3;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_filtrarLista;
    private javax.swing.JTextField buscadorReporte;
    private javax.swing.JPanel cont_piePagina;
    private javax.swing.JPanel cont_piePagina1;
    private javax.swing.JPanel cont_piePagina2;
    private javax.swing.JPanel cont_piePagina3;
    private javax.swing.JPanel cont_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_infoCliente;
    private javax.swing.JLabel lbl_infoCliente2;
    private javax.swing.JLabel lbl_infoEmpleado;
    private javax.swing.JLabel lbl_infoEmpleado1;
    private javax.swing.JComboBox<String> list_buscador;
    private javax.swing.JPanel panelInicial;
    private javax.swing.JPanel piePagina;
    private javax.swing.JTable tabla_articuloInterna;
    private javax.swing.JScrollPane tabla_articuloPrincipal;
    private javax.swing.JTable tabla_clienteInterna;
    private javax.swing.JScrollPane tabla_clientePrincipal;
    private javax.swing.JTable tabla_empleadoInterna;
    private javax.swing.JScrollPane tabla_empleadoPrincipal;
    private javax.swing.JTable tabla_empleadoxarticulo;
    private javax.swing.JScrollPane tabla_principalVentas;
    private javax.swing.JScrollPane tabla_principal_empleadoxarticulo;
    private javax.swing.JScrollPane tabla_principal_resultadoGenerales;
    private javax.swing.JTable tabla_resultadoGeneral;
    private javax.swing.JTable tabla_ventas;
    private javax.swing.JPanel tituloCliente;
    private javax.swing.JPanel tituloCliente2;
    private javax.swing.JPanel tituloEmpleado;
    private javax.swing.JPanel tituloEmpleado1;
    // End of variables declaration//GEN-END:variables
}
