package interfaz;

public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
        
        //Maximizar el formulario
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArticulos = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenuItem();
        menuReporte = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArticulos.setMnemonic('f');
        menuArticulos.setText("Archivo");
        menuArticulos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        menuClientes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        menuClientes.setMnemonic('c');
        menuClientes.setText("Gestión Clientes");
        menuClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuClientes.setMargin(new java.awt.Insets(10, 2, 10, 2));
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuArticulos.add(menuClientes);

        saveMenuItem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        saveMenuItem.setMnemonic('e');
        saveMenuItem.setText("Gestión Empleados");
        saveMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveMenuItem.setMargin(new java.awt.Insets(10, 2, 10, 2));
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        menuArticulos.add(saveMenuItem);

        saveAsMenuItem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Gestión Artículos");
        saveAsMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveAsMenuItem.setMargin(new java.awt.Insets(10, 2, 10, 2));
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        menuArticulos.add(saveAsMenuItem);

        menuVentas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        menuVentas.setMnemonic('v');
        menuVentas.setText("Gestión Ventas");
        menuVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuVentas.setMargin(new java.awt.Insets(10, 2, 10, 2));
        menuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActionPerformed(evt);
            }
        });
        menuArticulos.add(menuVentas);

        menuReporte.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        menuReporte.setMnemonic('r');
        menuReporte.setText("Reportes");
        menuReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReporte.setMargin(new java.awt.Insets(10, 2, 10, 2));
        menuReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteActionPerformed(evt);
            }
        });
        menuArticulos.add(menuReporte);

        menuSalir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        menuSalir.setMnemonic('x');
        menuSalir.setText("salir");
        menuSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSalir.setMargin(new java.awt.Insets(10, 2, 10, 2));
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuArticulos.add(menuSalir);

        menuBar.add(menuArticulos);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");
        helpMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("info 1");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('i');
        aboutMenuItem.setText("info 2");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteActionPerformed
        //Redireccionar al formulario de gestion de empleados
       
       frmReporte reporte = new frmReporte();
       Escritorio.add(reporte);
       
       //mostrar el formulario
       reporte.show();  
    }//GEN-LAST:event_menuReporteActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
       //Redireccionar al formulario de gestion de empleados
       
       frmEmpleados empleados = new frmEmpleados();
       Escritorio.add(empleados);
       
       //mostrar el formulario
       empleados.show();  
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
       //Redireccionar al formulario de  gestion de clientes
       
       frmClientes clientes = new frmClientes();
       Escritorio.add(clientes);
       
       //mostrar el formulario
       clientes.show();       
    }//GEN-LAST:event_menuClientesActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
       //Redireccionar al formulario de  gestion de clientes
       
       frmArticulos articulos = new frmArticulos();
       Escritorio.add(articulos);
       
       //mostrar el formulario
       articulos.show();  
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void menuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActionPerformed
       frmVentas ventas = new frmVentas();
       Escritorio.add(ventas);
       
       //mostrar el formulario
       ventas.show(); 
    }//GEN-LAST:event_menuVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu menuArticulos;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuReporte;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuVentas;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
